name: py5coding
channels:
  - conda-forge
dependencies:
  - colour>=0.1.5
  - jpype1>=1.6
  - jupyterlab
  - line_profiler>=4.2
  - matplotlib>=3.10
  - numpy>=2.2
  - pillow>=11.0
  - pip
  - python=3.11
  - shapely>=2.0
  - svgpathtools>=1.7
  - trimesh>=4.6
  - pip:
      - py5[jupyter]
